name:                advent-of-code-haskell
version:             0.1.0.0
github:              "trevorriles/advent-of-code-2019"
license:             BSD3
author:              "Trevor Riles"
maintainer:          "trevor@trevorriles.com"
copyright:           "Trevor Riles"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/trevorriles/advent-of-code-2019#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- split
- lens
- containers

library:
  source-dirs: src
  ghc-options:
  - -Wall
